### PR TITLE
Update small_examples.cpp

### PR DESCRIPTION
**Pull request by akumta**

### CODE REVIEW

**Comment by akumta** [comment]
For ticket# 11089

**Comment by apolukhin** [comment]
Thanks for providing the patch!

**Comment by akumta** [comment]
Can this be merged to the master branch?
The fix has not made it to Boost 1.58 rc2.

Thanks.

**Comment by apolukhin** [comment]
This will make it's way into 1.58.

Currently we have a "code freeze", until the beta gets stable. After releasing the beta, there'll be time for merging fixes for the 1.58 release and fixing issues in beta

**Pull request merged**
